services:
  - type: web
    name: tg-music-bot-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: VK_TOKEN
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE
        sync: false
      - key: CHAT_ID
        sync: false
      - key: PORT
        value: 10000
